name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Use the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the version of Node.js you need

      - name: Build and deploy
  
        run: |
          # Replace these build and deployment commands with your specific setup
          npm install
          npm run build
          npx gh-pages -d dist  # Replace with your deployment command

